//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDatabaseFirstExample.Data.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExceptionLog
    {
        public long Id { get; set; }
        public System.DateTime Created { get; set; }
        public string ServerName { get; set; }
        public string Message { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public string StackTrace { get; set; }
        public string InnerException { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
